# Generated by Django 2.2.3 on 2019-07-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20190728_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='date_created',
        ),
    ]
