# Generated by Django 2.2.3 on 2019-07-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20190728_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='author',
            field=models.TextField(default='Pankaj'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='date_created',
            field=models.DateField(default='2019-07-28'),
        ),
    ]
