# Generated by Django 2.2.3 on 2019-07-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20190728_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='author',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateField(),
        ),
    ]
