# Generated by Django 2.2.3 on 2019-07-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20190728_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='date_created',
        ),
    ]
